Json:
  context: Entity
  model: LegalEntity
  table: legal_entities
  fields:
    - name:string
    - short_name:string
    - public_name:string
    - status:string
    - type:string
    - owner_property_type:string
    - legal_form:string
    - edrpou:integer
    - kveds:array
    - addresses:array
    - phones:array
    - emails:array
    - active:boolean
    - created_by:string
    - updated_by:string
    - msp_id:references:msps

Json:
  context: Entity
  model: MSP
  table: msps
  fields:
    - accreditation:array
    - license:array
    - legal_entity:references:legal_entities

Json:
  context: Entity
  model: Product
  table: products
  fields:
    - name:string
    - parameters:map

Json:
  context: Entity
  model: CapitationContract
  table: capitation_contracts
  fields:
    - msp_id:string
    - status:string
    - services:map
    - start_date:datetime
    - end_date:datetime
    - signed_at:datetime
    - product_id:references:products

Json:
  context: Entity
  model: Division
  table: divisions
  fields:
    - msp_id:references:msps
    - external_id:string
    - name:string
    - type:string
    - mountain_group:string
    - address:array
    - phones:array
    - emails:string

Json:
  context: Staff
  model: Employee
  table: employees
  fields:
    - position:string
    - status:string
    - employee_type:string
    - active:boolean
    - created_by:string
    - updated_by:string
    - start_date:datetime
    - end_date:datetime
    - legal_entity_id:references:legal_entities
    - division_id:references:divisions
    - party_id:references:party_id
    - employee_doctor_id:references:employee_doctors

Json:
  context: Staff
  model: EmployeeDoctor
  table: employee_doctors
  fields:
    - education:array
    - qualification:array
    - specialities:array
    - science_degree:array
    - employee_id:references:employee

Json:
  context: Staff
  model: Party
  table: parties
  fields:
    - first_name:string
    - second_name:string
    - last_name:string
    - birth_date:date
    - gender:integer
    - tax_id:string
    - national_id:string
    - documents:array
    - phones:array
    - created_by:string
    - updated_by:string
    - employee_id:references:employee
    - doctor_id:references:doctors

Json:
  context: Staff
  model: Doctor
  table: doctors
  fields:
    - education:array
    - qualification:array
    - speciality:string
    - professional_level:array
    - science_degree:array
    - academic_degree:array
    - specialization:array
    - party_id:references:parties

Json:
  context: Log
  model: LogChanges
  table: changes
  fields:
    - user_id:string
    - resource:string
    - what_changed:map