Json:
  context: Entities
  model: LegalEntity
  table: legal_entities
  fields:
    - name:string
    - short_name:string
    - public_name:string
    - status:string
    - type:string
    - owner_property_type:string
    - legal_form:string
    - edrpou:string
    - kveds:map
    - addresses:map
    - phones:map
    - email:string
    - active:boolean
    - created_by:string
    - updated_by:string
    - msp_id:references:medical_service_providers
    - capitation_contract_id:references:medical_service_providers

Json:
  context: Entities
  model: MSP
  table: medical_service_providers
  fields:
    - accreditation:map
    - license:map
    - legal_entity_id:references:legal_entities

Json:
  context: Entities
  model: Division
  table: divisions
  fields:
    - external_id:string
    - name:string
    - type:string
    - mountain_group:string
    - address:map
    - phones:map
    - email:string
    - legal_entity_id:references:legal_entities

Json:
  context: Contracts
  model: Product
  table: products
  fields:
    - name:string
    - parameters:map

Json:
  context: Contracts
  model: CapitationContract
  table: capitation_contracts
  fields:
    - msp_id:string
    - status:string
    - services:map
    - start_date:datetime
    - end_date:datetime
    - signed_at:datetime
    - product_id:references:products

Json:
  context: Employees
  model: Employee
  table: employees
  fields:
    - position:string
    - status:string
    - employee_type:string
    - active:boolean
    - created_by:string
    - updated_by:string
    - start_date:datetime
    - end_date:datetime
    - legal_entity_id:references:legal_entities
    - division_id:references:divisions
    - party_id:references:party_id
    - employee_doctor_id:references:employee_doctors

Json:
  context: Employees
  model: EmployeeDoctor
  table: employee_doctors
  fields:
    - education:map
    - qualification:map
    - specialities:map
    - science_degree:map
    - employee_id:references:employee

Json:
  context: Parties
  model: Party
  table: parties
  fields:
    - first_name:string
    - second_name:string
    - last_name:string
    - birth_date:date
    - gender:integer
    - tax_id:string
    - national_id:string
    - documents:map
    - phones:map
    - created_by:string
    - updated_by:string
    - employee_id:references:employee
    - doctor_id:references:doctors

Json:
  context: Logs
  model: LogChanges
  table: changes
  fields:
    - user_id:string
    - resource:string
    - what_changed:map